App\Entity\Location:
    properties:
        latitude:
            - Range:
                min: -90
                max: 90
                notInRangeMessage: Latitude must be between {{ min }} and {{ max }}
                groups: ['new', 'edit']
        longitude:
            - Range:
                min: -180
                max: 180
                notInRangeMessage: Longitude must be between {{ min }} and {{ max }}
                groups: ['new', 'edit']
        city:
            - NotBlank: 
                groups: ['new', 'edit']
              
        country:
            - NotBlank: 
                groups: ['new', 'edit']
              